/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.praktikum9dan10;

import java.sql.ResultSet;
import java.sql.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nayandra
 */
public class FMataKuliah extends javax.swing.JFrame {
    public Connection conn;
    public Statement cn;

    /**
     * Creates new form FMataKuliah
     */
    public FMataKuliah() {
        initComponents();
        tampilData();
          bersih();
    }
    
    public void bersih(){
        kode.setText("");
        nama.setText("");
        sks.setText("");
    }
    
    // koneksi ke data base
    public void koneksi() {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/praktikum9_10","root", "");
            cn = conn.createStatement();
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null,"koneksi gagal..");
            System.out.println(e.getMessage());
        }
    }
    
    
    public void tampilData() {
        DefaultTableModel tabelnyo = new DefaultTableModel();
        tabelnyo.addColumn("Kode Mata Kuliah");
        tabelnyo.addColumn("Mata Kuliah");
        tabelnyo.addColumn("SKS");
        
        try {
            koneksi();
            var sql = "SELECT * FROM mata_kuliah";
            ResultSet rs = cn.executeQuery(sql);
            while (rs.next()) {                
                tabelnyo.addRow(new Object[] {
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                });
            }
            jTable1.setModel(tabelnyo);
            
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Ada Kesalahan");
        }
    }
    
    public void validasiMataKuliah() {
        try{
            koneksi();
            var sql = "SELECT * FROM mata_kuliah WHERE kode_mata_kuliah='" + kode.getText() + "'";
            ResultSet rs = cn.executeQuery(sql);
            if(rs.next()) {
                kode.setText(rs.getString("kode_mata_kuliah"));
                nama.setText(rs.getString("nama"));
                sks.setText(rs.getString("sks"));
                
                editTmbl.setEnabled(true);
                simpanTmbl.setEnabled(false);
                
                try {
                    int kel = JOptionPane.showConfirmDialog(this, "Kode matakuliah " + kode.getText() + " Sudah ada, mau diedit atau di hapus?", "INFORMASI", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if(kel == JOptionPane.NO_OPTION) {
                        bersih();
                        editTmbl.setEnabled(true);
                        simpanTmbl.setEnabled(true);
                        kode.requestFocus();
                        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    }
                }catch(Exception e) {
                    
                }
            }
        }catch(Exception e) {
            
        }
    }
    
    // cari matakuliah
    public void cari() {
        var a = new String(cari.getText());
        if(a.equals("")){
            JOptionPane.showConfirmDialog(null, "Field masih kosong..", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);
            cari.requestFocus();
        } else {
           DefaultTableModel tblmatkul= new DefaultTableModel();
           tblmatkul.addColumn("KODE_MTK");
           tblmatkul.addColumn(" NAMA_MTK");
           tblmatkul.addColumn("SKS");
           
           try{
               koneksi();
               var sql = "SELECT * FROM mata_kuliah WHERE kode_mata_kuliah LIKE '%" + cari.getText() + "%' or nama LIKE '%" + cari.getText() + "%'";
               ResultSet rs = cn.executeQuery(sql);
               while (rs.next()) {                   
                   tblmatkul.addRow(new Object[] {
                      rs.getString(1),
                      rs.getString(2),
                      rs.getString(3),
                   });
               }
               jTable1.setModel(tblmatkul);
           }catch(Exception e) {
               JOptionPane.showMessageDialog(null, "Data tidakditemukan..","INFORMASI",JOptionPane.INFORMATION_MESSAGE);
           }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kode = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        sks = new javax.swing.JTextField();
        simpanTmbl = new javax.swing.JButton();
        editTmbl = new javax.swing.JButton();
        hapusTmbl = new javax.swing.JButton();
        keluarTmbl = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        jLabel1.setText("INPUT DATA MATA KULIAH");

        jLabel2.setText("Cari Berdasarkan Nama Mata Kuliah");

        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        jLabel3.setText("KODE MATA KULIAH");

        jLabel4.setText("NAMA MATA KULIAH");

        jLabel5.setText("SKS");

        kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeActionPerformed(evt);
            }
        });

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        sks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sksActionPerformed(evt);
            }
        });

        simpanTmbl.setText("SIMPAN");
        simpanTmbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanTmblActionPerformed(evt);
            }
        });

        editTmbl.setText("EDIT");
        editTmbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTmblActionPerformed(evt);
            }
        });

        hapusTmbl.setText("DELETE");
        hapusTmbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusTmblActionPerformed(evt);
            }
        });

        keluarTmbl.setText("KELUAR");
        keluarTmbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarTmblActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(keluarTmbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(sks, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hapusTmbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editTmbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(kode, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(56, 56, 56)
                                    .addComponent(simpanTmbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(187, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cari)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(simpanTmbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editTmbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(sks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hapusTmbl))
                        .addGap(18, 18, 18)
                        .addComponent(keluarTmbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeActionPerformed
        // TODO add your handling code here:
        validasiMataKuliah();
    }//GEN-LAST:event_kodeActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void sksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sksActionPerformed

    private void simpanTmblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanTmblActionPerformed
        // TODO add your handling code here:
        try{
            koneksi();
            var sql = "INSERT INTO mata_kuliah VALUES('"+ kode.getText() + "','" + nama.getText() + "','" + sks.getText() + "')";
            cn.execute(sql);
            conn.close();
            tampilData();
//            bersih();
            JOptionPane.showMessageDialog(null,"Data berhasil di simpan");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Proses penyimpanan gagal" + e);
        }
    }//GEN-LAST:event_simpanTmblActionPerformed

    private void editTmblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTmblActionPerformed
        // TODO add your handling code here:
        try{
            koneksi();
            var sql = "update mata_kuliah set nama='"+ nama.getText() +"'," +"sks='" + sks.getText() + "'" +"where kode_mata_kuliah='" + kode.getText() + "'";
            cn.executeUpdate(sql);
            cn.close();
            tampilData();
            bersih();
            kode.setEnabled(true);
            simpanTmbl.setEnabled(true);
            kode.requestFocus();
            editTmbl.setEnabled(false);
            hapusTmbl.setEnabled(false);
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_editTmblActionPerformed

    private void hapusTmblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusTmblActionPerformed
        // TODO add your handling code here:
        try{
            getToolkit().beep();
            int keluar = JOptionPane.showConfirmDialog(this, "Anda Yakin Ingin MeghapusIni..?","PERINGATAN",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
            if(keluar == JOptionPane.YES_OPTION){
                try{
                    koneksi();
                    var sql = "DELETE FROM mata_kuliah WHERE kode_mata_kuliah = '" + kode.getText() + "'";
                    cn.executeUpdate(sql);
                    cn.close();
                    tampilData();
                    bersih();
                    kode.setEnabled(true);
                    simpanTmbl.setEnabled(true);
                    editTmbl.setEnabled(false);
                    hapusTmbl.setEnabled(false);
                    kode.requestFocus();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Deleting failed.." + e.getMessage());
                }
            }
        }catch(Exception e){
           
        }
    }//GEN-LAST:event_hapusTmblActionPerformed

    private void keluarTmblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarTmblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keluarTmblActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int tabel = jTable1.getSelectedRow();
        var a = jTable1.getValueAt(tabel, 0).toString();
        var b = jTable1.getValueAt(tabel, 1).toString();
        var c = jTable1.getValueAt(tabel, 2).toString();
        
        kode.setText(a);
        nama.setText(b);
        sks.setText(c);
        
        kode.setEnabled(false);
        simpanTmbl.setEnabled(false);
        editTmbl.setEnabled(true);
        hapusTmbl.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_cariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMataKuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMataKuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMataKuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMataKuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMataKuliah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cari;
    private javax.swing.JButton editTmbl;
    private javax.swing.JButton hapusTmbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton keluarTmbl;
    private javax.swing.JTextField kode;
    private javax.swing.JTextField nama;
    private javax.swing.JButton simpanTmbl;
    private javax.swing.JTextField sks;
    // End of variables declaration//GEN-END:variables
}
